import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import Nav from "@/components/nav/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-[17fr_83fr] h-screen">
          <Sidebar />
          <div>
            <Nav />
            <div className="py-10 px-12">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
